env:
  env_id: "custom_adversarial_pursuit"
  log_dir: "./logs/iql_adversarial/"
  logger: "tensorboard"  # Choices: tensorboard, wandb.
  project_name: ""
  wandb_user_name: ""
  render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
  device: "cpu"
  minimap_mode: False
  max_cycles: 1000 # number of env.steps in an episode
  extra_features: False
  map_size: 16
  seed: 1
  running_steps: 5_000_000
  render_episode_period: 20
agents:
-
  test_mode: False
  model_dir_load: ""
  model_dir_save: "./models/iql_adversarial/"
  model_checkpoint_period: 100000
  load_policy_only: False
  reset_optimizer: False
  algorithm: "IQL"
  side_name: "predator"
  layer_type: "Linear"
  hidden_layers: [64]
  hidden_mean_layers: [64]
  activation: "ReLU"

  buffer_size: 10000
  batch_size: 256
  learning_start: 10000
  learning_rate: 0.001
  gamma: 0.99  # red expects future rewards
  tau: 0.005

  start_greedy: 1.0
  end_greedy: 0.05
  greedy_decay_steps: 20_000
  train_period: 128
  target_network_train_period: 256
-
  test_mode: False
  model_dir_load: ""
  model_dir_save: "./models/iql_adversarial/"
  model_checkpoint_period: 100000
  load_policy_only: False
  reset_optimizer: False
  algorithm: "IQL"
  side_name: "prey"
  layer_type: "Linear"
  hidden_layers: [64]
  hidden_mean_layers: [64]
  activation: "ReLU"

  buffer_size: 10000
  batch_size: 256
  learning_start: 10000
  learning_rate: 0.001
  gamma: 0.99  # red expects future rewards
  tau: 0.005

  start_greedy: 1.0
  end_greedy: 0.05
  greedy_decay_steps: 20_000
  train_period: 128
  target_network_train_period: 256
