env:
  env_id: "custom_battle"
  log_dir: "./logs/mfq_test/"
  project_name: "MAgent2"
  logger: "tensorboard"  # Choices: tensorboard, wandb.
  wandb_user_name: "your_user_name"
  render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
  device: "cpu"
  minimap_mode: False
  max_cycles: 2000 # number of env.steps in an episode
  extra_features: False
  map_size: 20
  seed: 1
  running_steps: 250000
  render_episode_period: 5

agents:
-
  test_mode: False
  model_dir_load: "./models/mfq_test/2024-4-2_0:7:2/red"
  model_dir_save: "./models/mfq_test/"
  model_checkpoint_period: 50000
  load_policy_only: False
  reset_optimizer: False
  algorithm: "MFQ"  # the learning algorithms_marl
  side_name: "red"
  layer_type: "Linear"
  hidden_layers: [64, ]
  hidden_mean_layers: [64, ]
  activation: "ReLU"

  buffer_size: 20000
  batch_size: 32
  learning_start: 100
  learning_rate: 0.001
  gamma: 0.95  # red expects future rewards
  tau: 0.005

  start_greedy: 0.5
  end_greedy: 0.05
  temperature: 0.1
  train_per_step: False  # True: train model per step; False: train model per episode.
  train_period: 10
  target_network_train_period: 20
  sync_period: 100

  use_grad_clip: False
  grad_clip_norm: 0.5

  eval_interval: 100000
  test_episode: 5

-
  test_mode: False
  model_dir_load: ""
  model_dir_save: "./models/mfq_test/"
  model_checkpoint_period: 50000
  load_policy_only: False
  reset_optimizer: False
  algorithm: "MFQ"  # the learning algorithms_marl
  side_name: "blue"
  layer_type: "Linear"
  hidden_layers: [64,]
  hidden_mean_layers: [64, ]
  activation: "ReLU"

  buffer_size: 20000
  batch_size: 32
  learning_start: 1000
  learning_rate: 0.001
  gamma: 0.3  # blue is greedy
  tau: 0.005

  start_greedy: 0.5
  end_greedy: 0.05
  temperature: 0.1
  train_per_step: False  # True: train model per step; False: train model per episode.
  train_period: 10
  target_network_train_period: 20
  sync_period: 100

  use_grad_clip: False
  grad_clip_norm: 0.5

  eval_interval: 100000
  test_episode: 5
