env:
  env_id: "custom_adversarial_pursuit"
  log_dir: "./logs/iql/"
  model_dir: "./models/iql/"
  project_name: "MAgent2"
  logger: "tensorboard"  # Choices: tensorboard, wandb.
  wandb_user_name: "your_user_name"
  render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
  test_mode: False
  device: "cpu"
  minimap_mode: False
  max_cycles: 500 # number of env.steps in an episode
  extra_features: False
  map_size: 42
  seed: 1
  running_steps: 10000

agents:
-
  algorithm: "IQL"  # the learning algorithms_marl
  side_name: "predator"
  layer_type: "Linear"
  hidden_layers: [64, ]
  activation: "ReLU"

  buffer_size: 20000
  batch_size: 2
  learning_start: 50
  learning_rate: 0.001
  gamma: 0.95  # discount factor
  double_q: True  # use double q learning
  tau: 0.005

  start_greedy: 0.5
  end_greedy: 0.05
  decay_step_greedy: 2500000
  start_training: 1000  # start training after n episodes
  train_per_step: False  # True: train model per step; False: train model per episode.
  train_period: 1
  target_network_train_period: 1
  sync_period: 100

  use_grad_clip: False
  grad_clip_norm: 0.5

  eval_interval: 100000
  test_episode: 5

-
  algorithm: "IQL"  # the learning algorithms_marl
  side_name: "prey"
  layer_type: "Linear"
  hidden_layers: [64, ]
  activation: "ReLU"

  buffer_size: 20000
  batch_size: 2
  learning_start: 50
  learning_rate: 0.001
  gamma: 0.95  # discount factor
  double_q: True  # use double q learning
  tau: 0.005 # target network update step

  start_greedy: 0.5
  end_greedy: 0.05
  decay_step_greedy: 2500000
  start_training: 1000  # start training after n episodes
  train_per_step: False  # True: train model per step; False: train model per episode.
  train_period: 1
  target_network_train_period: 1
  sync_period: 100

  use_grad_clip: False
  grad_clip_norm: 0.5

  eval_interval: 100000
  test_episode: 5
